import { Injectable } from '@nestjs/common';
import { buildAmortization, type AmortizationParams } from '@mara/mortgage-calc';
import PDFDocument from 'pdfkit';

const NAVY = '#0F2A4A';
const TEXT = '#10202F';
const MUTED = '#5A6B7C';
const BORDER = '#E1E6EC';

const MARGIN = 40;
const ROW_HEIGHT = 16;
// Column x-positions and widths for the 5-column table on US Letter (612pt wide).
const COLS = [
  { label: '#', x: 40, width: 40, align: 'left' as const },
  { label: 'Payment', x: 80, width: 110, align: 'right' as const },
  { label: 'Interest', x: 190, width: 110, align: 'right' as const },
  { label: 'Principal', x: 300, width: 110, align: 'right' as const },
  { label: 'Balance', x: 410, width: 160, align: 'right' as const },
];

function money(value: number): string {
  return value.toLocaleString('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 2,
  });
}

@Injectable()
export class AmortizationPdfService {
  /**
   * Renders the authoritative amortization schedule (recomputed server-side
   * from the shared engine — never client-supplied rows) as a PDF buffer.
   */
  async render(params: AmortizationParams & { label?: string }): Promise<Buffer> {
    const result = buildAmortization(params);

    // compress:false keeps text operators greppable, which lets tests assert
    // the PDF actually contains the expected figures.
    const doc = new PDFDocument({ size: 'LETTER', margin: MARGIN, compress: false });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    const done = new Promise<Buffer>((resolve) =>
      doc.on('end', () => resolve(Buffer.concat(chunks))),
    );

    // Header
    doc.fillColor(NAVY).fontSize(18).font('Helvetica-Bold').text('Mara Mortgage');
    doc.fillColor(TEXT).fontSize(13).text('Amortization Schedule');
    if (params.label !== undefined && params.label !== '') {
      doc.fillColor(MUTED).fontSize(10).font('Helvetica').text(params.label);
    }
    doc.moveDown(0.5);
    doc
      .fillColor(MUTED)
      .fontSize(9)
      .font('Helvetica')
      .text(
        `Loan ${money(params.principal)}  ·  ${params.annualRatePct}% APR  ·  ${params.termMonths} months  ·  ` +
          `Payment ${money(result.monthlyPayment)}  ·  Total interest ${money(result.totalInterest)}  ·  Total paid ${money(result.totalPaid)}`,
      );
    doc.moveDown(0.5);

    const drawTableHeader = (): void => {
      const y = doc.y;
      doc.font('Helvetica-Bold').fontSize(8).fillColor(NAVY);
      for (const col of COLS) {
        doc.text(col.label, col.x, y, { width: col.width, align: col.align });
      }
      doc
        .moveTo(MARGIN, y + ROW_HEIGHT - 4)
        .lineTo(572, y + ROW_HEIGHT - 4)
        .strokeColor(BORDER)
        .stroke();
      doc.y = y + ROW_HEIGHT;
      doc.font('Helvetica').fontSize(8).fillColor(TEXT);
    };

    drawTableHeader();
    const bottomLimit = doc.page.height - MARGIN - ROW_HEIGHT;
    for (const row of result.schedule) {
      if (doc.y > bottomLimit) {
        doc.addPage();
        drawTableHeader();
      }
      const y = doc.y;
      const cells = [
        String(row.paymentNumber),
        money(row.payment),
        money(row.interest),
        money(row.principal),
        money(row.balance),
      ];
      cells.forEach((cell, i) => {
        const col = COLS[i];
        if (col !== undefined) {
          doc.text(cell, col.x, y, { width: col.width, align: col.align });
        }
      });
      doc.y = y + ROW_HEIGHT;
    }

    doc.moveDown(1);
    doc
      .fontSize(7)
      .fillColor(MUTED)
      .text(
        'Estimates for planning purposes only — not a loan offer or commitment to lend. Generated by the Mara Mortgage app.',
        MARGIN,
        undefined,
        { width: 532 },
      );

    doc.end();
    return done;
  }
}
