import type { paths } from '@mara/shared-types';
import createClient, { type Middleware } from 'openapi-fetch';

import { useAuthStore } from '@/features/auth/store';

/**
 * Typed API client — every route, param, and response shape comes from the
 * OpenAPI spec generated by the backend, so mobile/API drift is a compile error.
 *
 * Base URL resolution:
 * - EXPO_PUBLIC_API_URL when set (real devices need the laptop's LAN IP,
 *   e.g. http://10.0.0.227:3001 — localhost on a phone points at the phone).
 * - localhost fallback for web preview and simulators.
 */
export const API_BASE_URL = process.env.EXPO_PUBLIC_API_URL ?? 'http://localhost:3001';
const baseUrl = API_BASE_URL;

/** Authenticated fetch for non-JSON responses (e.g. PDF downloads). */
export async function fetchBinary(path: string, init?: RequestInit): Promise<Response> {
  const token = useAuthStore.getState().accessToken;
  const headers = new Headers(init?.headers);
  if (token !== null) headers.set('Authorization', `Bearer ${token}`);
  return fetch(`${API_BASE_URL}${path}`, { ...init, headers });
}

const authMiddleware: Middleware = {
  onRequest({ request }) {
    const token = useAuthStore.getState().accessToken;
    if (token !== null && !request.headers.has('Authorization')) {
      request.headers.set('Authorization', `Bearer ${token}`);
    }
    return request;
  },
};

export const api = createClient<paths>({ baseUrl });
api.use(authMiddleware);
