import type { paths } from '@mara/shared-types';
import createClient from 'openapi-fetch';

/**
 * Typed API client — every route, param, and response shape comes from the
 * OpenAPI spec generated by the backend, so mobile/API drift is a compile error.
 *
 * Base URL resolution:
 * - EXPO_PUBLIC_API_URL when set (real devices need the laptop's LAN IP,
 *   e.g. http://10.0.0.227:3001 — localhost on a phone points at the phone).
 * - localhost fallback for web preview and simulators.
 */
const baseUrl = process.env.EXPO_PUBLIC_API_URL ?? 'http://localhost:3001';

export const api = createClient<paths>({ baseUrl });
