import type { CSSProperties } from 'react';

/** Shared admin UI styles — one visual language across content screens. */
export const ui: Record<string, CSSProperties> = {
  h1: { fontSize: 22, color: '#10202F', margin: '8px 0 0' },
  h2: { fontSize: 16, color: '#10202F', margin: '18px 0 0' },
  card: {
    background: '#FFFFFF',
    border: '1px solid #E1E6EC',
    borderRadius: 12,
    padding: 20,
  },
  table: { width: '100%', borderCollapse: 'collapse' as const, fontSize: 14 },
  th: {
    textAlign: 'left' as const,
    color: '#5A6B7C',
    fontSize: 12,
    textTransform: 'uppercase' as const,
    padding: '8px 10px',
    borderBottom: '1px solid #E1E6EC',
  },
  td: { padding: '10px', borderBottom: '1px solid #F0F3F6', color: '#10202F' },
  badgeOn: {
    background: '#E5F3EC',
    color: '#1F7A4D',
    borderRadius: 999,
    padding: '2px 10px',
    fontSize: 12,
    fontWeight: 600,
  },
  badgeOff: {
    background: '#F0F3F6',
    color: '#5A6B7C',
    borderRadius: 999,
    padding: '2px 10px',
    fontSize: 12,
    fontWeight: 600,
  },
  button: {
    background: '#0F2A4A',
    color: '#FFFFFF',
    border: 'none',
    borderRadius: 6,
    padding: '10px 16px',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
  },
  buttonSecondary: {
    background: '#FFFFFF',
    color: '#0F2A4A',
    border: '1px solid #0F2A4A',
    borderRadius: 6,
    padding: '9px 15px',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    textDecoration: 'none',
    display: 'inline-block',
  },
  label: {
    fontSize: 13,
    color: '#5A6B7C',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
  },
  input: {
    border: '1px solid #E1E6EC',
    borderRadius: 6,
    padding: '10px 12px',
    fontSize: 15,
    color: '#10202F',
    fontFamily: 'inherit',
  },
  textarea: {
    border: '1px solid #E1E6EC',
    borderRadius: 6,
    padding: '10px 12px',
    fontSize: 14,
    color: '#10202F',
    fontFamily: 'inherit',
    minHeight: 220,
    lineHeight: 1.5,
    resize: 'vertical' as const,
  },
  error: { color: '#B3261E', fontSize: 13, margin: 0 },
  success: { color: '#1F7A4D', fontSize: 13, margin: 0 },
  muted: { color: '#5A6B7C', fontSize: 13 },
  link: { color: '#0F2A4A', fontWeight: 600 },
};
